spring:

  datasource:
    url: jdbc:mysql://localhost:3306/grepp_dao
    username: happy
    password: jieun

  jpa:
    hibernate:
      ddl-auto: create


mybatis:
  type-aliases-package: io.jieun.dao.global.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
